version: '3'
services:
  proxysql:
    container_name: proxysql
    image: dataindataout/docker-proxysql
    hostname: proxysql
    volumes:
      - ./conf/proxysql.cnf:/etc/proxysql.cnf
    environment:
      - CLUSTER_NAME=test
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PROXY_USER=root
      - MYSQL_PROXY_PASSWORD=password
      - DISCOVERY_SERVICE=false
    expose:
      - "6032"
    ports:
      - "6032:6032"
      - "3306:3306"
  vault:
    container_name: vault
    hostname: vault
    image: dataindataout/docker-vault
    ports:
      - "8200:8200"
    volumes:
      - ./conf/vault.hcl:/etc/vault.hcl
    environment:
      - VAULT_ADDR=http://vault:8200
    command: "server -config=/etc/vault.hcl"

